# -*- coding: utf-8 -*-
"""ERI_E03 part B: MAIN01 — Cineria ambushes Eri outside the office in
her gothic-lolita outfit, reveals she knows about the real-idol work,
calls Ozaki a parasite ('Longhair'), and challenges Eri to the idol
showdown (no rules thought out yet). Dialogue <=38 chars/line, buttons
~13/line. Preserve ―㌍. Cineria netspeak: tera-cute, charisma-para=MAX,
now-thinking, -mon suffixes."""
import json

MAIN01 = {
    1: "Office",
    2: "Cineria!",
    3: "Cineria?",
    4: "Planaria?",
    5: "Acquaintance",
    6: "A friend",
    7: "Familiar face",
    8: "Ms. Ozaki,\nthe job...",
    9: "How will we\ncompete?",
    10: "Do your\nbest, okay?",
}

MAIN01_MES = {
    1: "Ozaki",
    2: "All right, Eri. Off to the worksite.",
    3: "Let's give it our best today, too",
    4: "Eri",
    5: "Okay. Where are we headed first?",
    6: "First up...",
    7: "???",
    8: "Sen-pai! Fooound you!",
    9: "Huh? That voice...",
    10: "Y-you're... the fairy from before!?",
    11: "No way, a real live girl!?",
    12: "You're...",
    13: "Cineria!",
    14: "Cineria",
    15: "That's right, it's MEEE!",
    16: "Straight out of the monitor,",
    17: "ta-da-da-da-DAAAH!",
    18: "Cineria?",
    19: "What's with the puzzled face?",
    20: "Obviously it's me, who else?",
    21: "No way there's more than one girl",
    22: "this charisma-para=MAX walking around♪",
    23: "Planaria?",
    24: "Hey! Don't botch my name right at",
    25: "the opening! It's Ci-ne-ri-a!",
    26: "Tera-cute me, popping out of the",
    27: "monitor, ta-da-da-dah♪",
    28: "Senpai! Caught you red-handed at last!",
    29: "You've been acting shady lately, so I",
    30: "checked―㌍and you're a REAL idol now!?",
    31: "Th-this is... um...",
    32: "And it's ALL because of... *glaaare*",
    33: "What? Something about me?",
    34: "Is this Longhair the culprit who",
    35: "dragged Senpai to the dark side?",
    36: "Eri, who is this girl?",
    37: "Cineria is... a net idol.",
    38: "Sometimes we chat online... she's...",
    39: "An acquaintance",
    40: "I see. An internet...",
    41: "That explains the outrageous outfit",
    42: "A friend",
    43: "I see. An internet...",
    44: "Didn't I tell you to keep your",
    45: "distance from that sort of crowd?",
    46: "Urgh... Ms. Ozaki's a little angry...",
    47: "I see. Now it all makes sense.",
    48: "Only someone with no social sense...",
    49: "...would walk around in public",
    50: "dressed as outrageously as this",
    51: "A familiar face",
    52: "I see. Someone you barely know, then",
    53: "Senpai, so MEAN!",
    54: "Honestly. Coming all this way to",
    55: "see you. And what's more...",
    56: "Out in public, dressed like that...",
    57: "Whaaat? You got a problem with my",
    58: "rare-mon gothic lolita look?",
    59: "This here's a premium-mon I scored",
    60: "by DMing a Cospureh clerk directly!",
    61: "Eri... what language is she speaking?",
    62: "Probably... Japanese",
    63: "And you can understand her?",
    64: "...More or less",
    65: "Senpai, quit this whole real-idol",
    66: "business right now, please!",
    67: "Or you'll get contaminated and your",
    68: "pure heart will go dark-side!",
    69: "Contaminated...? What are you on about",
    70: "I don't quite follow, but enough",
    71: "with the weird delusions",
    72: "YOU'RE the one who should cut it out!",
    73: "Our bond has flags raised everywhere,",
    74: "and you're trying to tear it apart!",
    75: "C'mon, Senpaaai? C'mon, c'mon...",
    76: "Sorry, Cineria.",
    77: "I've... got work to do",
    78: "Grrrrgh! After everything I said,",
    79: "you STILL don't get it!!!!",
    80: "That settles it, Senpai! A showdown!",
    81: "Huh? A showdown?",
    82: "Yes! Please face me",
    83: "in an idol showdown!",
    84: "And if I win, you wash your hands",
    85: "of this lame idol business!",
    86: "Excuse me, who said you could decide",
    87: "that? Listen here, you...",
    88: "Hmph! Gonna run away 'cause deep",
    89: "down you KNOW you're ruining Senpai?",
    90: "Managers are just parasites who",
    91: "feed off other people, after all!",
    92: "Para...site!?",
    93: "WHAT did you say!? Say that",
    94: "one more time, you little―㌍",
    95: "Ms. Ozaki... calm down?",
    96: "Haah, haah, haah...",
    97: "Fine! If you're going to mock us that",
    98: "far, we'll take your little showdown!",
    99: "But just once! We'll show you exactly",
    100: "how amazing a real idol is",
    101: "Ooh, scary. You heat up SO fast.",
    102: "Whew... *fan fan fan*...",
    103: "I've never seen Ms. Ozaki this mad...",
    104: "Come on, Eri, you say something",
    105: "to her too!",
    106: "Umm...",
    107: "Ms. Ozaki, the job...",
    108: "Huh?",
    109: "If we keep chatting... we'll be late",
    110: "Oh! That's right!",
    111: "How careless of me",
    112: "Cineria, we'll... do this another time",
    113: "Okay! And Senpai, I won't",
    114: "be going easy on you!",
    115: "I'll DEFINITELY win and put you",
    116: "back on the right path!",
    117: "Okay. Looking forward to it. Bye now",
    118: "First comes the job in front of me.",
    119: "Cineria can wait until after that",
    120: "How will we compete?",
    121: "How...??? Um, well...",
    122: "The date, the venue, regulations,",
    123: "the judging system...",
    124: "...What'll it be?",
    125: "Th-that's, er, well, um~ I haven't",
    126: "actually thought any of it out...",
    127: "You picked a fight on sheer momentum?",
    128: "Oh, sh-shut up! It's fine!",
    129: "I'm gonna figure it out NOW, okay?",
    130: "Hmmm. Hmmm...",
    131: "Ah! Eri, we can't stand around!",
    132: "We'll be late for the job!",
    133: "...Ah",
    134: "This can wait. Let's hurry",
    135: "Okay",
    136: "Ah, Senpai! Wait, please!",
    137: "I'm still thinking... Senpaaai!!!!",
    138: "No time to be chatting around...",
    139: "If we hurry now, we might make it",
    140: "Do your best, okay?",
    141: "Okay!",
    142: "Wait, Senpai. I'm your",
    143: "RIVAL right now, remember?",
    144: "You can't tell me to do my best!",
    145: "Then... don't do your best?",
    146: "Well, that's not happening either!",
    147: "........",
    148: "Then... what SHOULD I say?",
    149: "Umm... hmmm...",
    150: "You can't cheer me on, but if you're",
    151: "cold to me, that hurts too...",
    152: "Hmmm, hmmm, hmmmmm...",
    153: "Ah! Eri, this is bad!",
    154: "We can't stand around here!",
    155: "We'll be late for the job! Hurry",
    156: "...Ah, right",
    157: "W-wait, Senpai!",
    158: "Where are you going!?",
    159: "Sorry, we're in a hurry",
    160: "Nooo! I'm still now-thinking",
    161: "over here!!!",
    162: "We talked way too long.",
    163: "I might be seriously late for work...",
}

FILES = {
    "F_SCN/ERI_E03_MAIN01.BBQ": MAIN01,
    "F_SCN/ERI_E03_MAIN01_MES.BBQ": MAIN01_MES,
}

for rel, en in FILES.items():
    path = f"translation/{rel}.json"
    doc = json.load(open(path, encoding="utf-8"))
    for line in doc["lines"]:
        if line["i"] in en:
            line["en"] = en[line["i"]]
    problems = []
    for l in doc["lines"]:
        e = l.get("en", "")
        if not e and l["jp"].strip():
            problems.append(f"missing i={l['i']}")
        if e:
            try:
                e.encode("cp932")
            except UnicodeEncodeError:
                problems.append(f"not cp932 i={l['i']}: {e!r}")
            for part in e.split("\n"):
                if len(part) > 38:
                    problems.append(f"len {len(part)}>38 i={l['i']}: {part!r}")
    print(rel, "OK" if not problems else problems)
    json.dump(doc, open(path, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("done")
